In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import FactorAnalysis as FA


In [2]:
from sklearn.datasets import load_wine
data_df=load_wine()
data_df

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [3]:
x=data_df.data
y=data_df.target
print("Feature array shape:",x.shape)
print("Target array shape:",y.shape)

Feature array shape: (178, 13)
Target array shape: (178,)


In [4]:
from sklearn.preprocessing import StandardScaler
x_std=StandardScaler().fit_transform(x)
x_std

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x_std,y,test_size=0.3,random_state=0)

In [6]:
classifier=RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

In [7]:
cm=confusion_matrix(y_test,y_pred)
print("Confusion_matrix:\n",cm)
print("Accuracy:\n",accuracy_score(y_test,y_pred))


Confusion_matrix:
 [[19  0  0]
 [ 1 20  1]
 [ 0  0 13]]
Accuracy:
 0.9629629629629629


In [11]:
fa=FA(n_components=2)
fa_x_train=fa.fit_transform(x_train,y_train)
fa_x_test=fa.transform(x_test)

In [12]:
new_classifier=RandomForestClassifier(max_depth=2,random_state=0)
new_classifier.fit(fa_x_train,y_train)
new_y_pred=new_classifier.predict(fa_x_test)

In [13]:
new_cm=confusion_matrix(y_test,new_y_pred)
print("Confusion_matrix:\n",new_cm)
print("Accuracy:\n",accuracy_score(y_test,new_y_pred))

Confusion_matrix:
 [[18  1  0]
 [ 4 18  0]
 [ 0  0 13]]
Accuracy:
 0.9074074074074074


In [14]:
print(fa_x_train.shape)
print(fa_x_test.shape)

(124, 2)
(54, 2)
